version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MinhaSenhaSuperForte@123
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - sqlnet

  api:
    build: .
    hostname: api
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - sqlnet

volumes:
  sqlvolume:
    driver: local

networks:
  sqlnet:
    driver: bridge
